- explore the coinbase pro API directly with requests library
- get familiar with requests

# About requests

- post requests 
- get requests

# About the [coinbase pro API](https://docs.pro.coinbase.com/)

- __REST API__: 
    * The REST API has endpoints for account and order management as well as public market data.
    * REST API ENDPOINT URL
https://api.pro.coinbase.com



- __FIX API__: 
    * FIX (Financial Information eXchange) is a standard protocol which can be used to enter orders, submit cancel requests, and receive fills. Users of the FIX API will typically have existing software using FIX for order management. Users who are not familiar with FIX should first consider using the REST API.
    * FIX API ENDPOINT URL tcp+ssl://fix.pro.coinbase.com:4198

- **Websocket feed**: 
    * The websocket feed provides real-time market data updates for orders and trades.
    * wss://ws-feed.pro.coinbase.com

In [1]:
import requests
import pandas as pd

In [37]:
r = requests.get('https://api.pro.coinbase.com/products')

In [38]:
pd.DataFrame(r.json())

,id,base_currency,quote_currency,base_min_size,base_max_size,quote_increment,base_increment,display_name,min_market_funds,max_market_funds,margin_enabled,post_only,limit_only,cancel_only,trading_disabled,status,status_message
0,LRC-USD,LRC,USD,1.00000000,560000.00000000,0.00010000,0.00000100,LRC/USD,1.0,100000,False,False,False,False,False,online,
1,EOS-EUR,EOS,EUR,0.10000000,50000.00000000,0.00100000,0.10000000,EOS/EUR,10,100000,False,False,False,False,False,online,
2,CGLD-USD,CGLD,USD,0.10000000,34000.00000000,0.00010000,0.01000000,CGLD/USD,1.0,100000,False,False,False,False,False,online,
3,XTZ-BTC,XTZ,BTC,1.00000000,100000.00000000,0.00000001,0.01000000,XTZ/BTC,0.001,10,False,False,False,False,False,online,
4,ALGO-USD,ALGO,USD,1.00000000,500000.00000000,0.00010000,1.00000000,ALGO/USD,10,100000,False,False,False,False,False,online,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,DAI-USDC,DAI,USDC,1.00000000,100000.00000000,0.00000100,0.00001000,DAI/USDC,5,100000,False,False,True,False,False,online,
121,FIL-USD,FIL,USD,0.01000000,3400.00000000,0.00010000,0.00100000,FIL/USD,1.0,100000,False,False,False,False,False,online,
122,NMR-BTC,NMR,BTC,0.01000000,3900.00000000,0.00000001,0.00100000,NMR/BTC,0.0001,10,False,False,False,False,False,online,
123,NMR-EUR,NMR,EUR,0.01000000,3900.00000000,0.00010000,0.00100000,NMR/EUR,1.0,100000,False,False,False,False,False,online,
124,BNT-EUR,BNT,EUR,1.00000000,95000.00000000,0.00010000,0.00000100,BNT/EUR,1.0,92000,False,False,False,False,False,online,

In [41]:
params={'start':'2021-01-25'
        , 'end':'2021-01-26'
       , 'granularity':3600}
r = requests.get('https://api.pro.coinbase.com/products/BTC-USD/candles', params=params )

In [44]:
pd.DataFrame(r.json())

             0         1         2         3         4            5
0   1611619200  31692.82  32680.00  32260.52  32493.71  1507.282542
1   1611615600  32208.88  32650.00  32455.44  32261.87  1117.078764
2   1611612000  31920.80  32730.07  32713.90  32460.56  1129.941454
3   1611608400  32164.68  33445.90  33445.90  32713.90  1778.387144
4   1611604800  33013.36  33445.90  33412.37  33445.90  1247.438166
5   1611601200  33364.92  33772.33  33648.78  33412.38   835.447131
6   1611597600  33500.10  34008.36  33760.63  33646.65   880.388579
7   1611594000  33675.10  34261.48  33898.00  33759.78  1119.012454
8   1611590400  33600.00  34618.34  34460.30  33898.00  2136.924450
9   1611586800  34202.03  34583.08  34462.96  34450.85   995.912130
10  1611583200  34362.06  34888.00  34578.24  34462.96  1303.993615
11  1611579600  34135.42  34699.76  34201.43  34574.39  1350.902438
12  1611576000  33063.13  34355.78  33188.21  34199.21  1066.500105
13  1611572400  33054.12  33348.75  33134.87  33188.21   232.612068
14  1611568800  32789.00  33173.27  32990.00  33137.50   277.554947
15  1611565200  32888.00  33549.82  33468.33  32994.16   393.015839
16  1611561600  33224.18  33507.80  33375.89  33456.87   234.197283
17  1611558000  33080.00  33566.87  33500.00  33376.25   359.179635
18  1611554400  33178.41  33566.33  33359.10  33499.99   412.174428
19  1611550800  33218.04  33471.34  33398.06  33356.55   595.216715
20  1611547200  33333.00  33793.43  33571.99  33393.80  1246.717209
21  1611543600  32603.99  33700.00  32797.42  33571.99  1453.885811
22  1611540000  32672.86  33000.00  32881.96  32791.52   788.972709
23  1611536400  32434.85  32911.00  32596.42  32877.45   817.781133
24  1611532800  32210.17  32850.00  32293.18  32596.42  1272.428729

In [56]:
params={'start':'2021-01-25'
        , 'end':'2021-01-26'
       , 'granularity':1}
r = requests.get('https://api.pro.coinbase.com/products/BTC-USD/trades', params=params )

In [57]:
r.json()

[{'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441724,
  'price': '46979.79000000',
  'size': '0.09788713',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441723,
  'price': '46980.26000000',
  'size': '0.04717170',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441722,
  'price': '46980.29000000',
  'size': '0.33400000',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441721,
  'price': '46983.09000000',
  'size': '0.42562898',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441720,
  'price': '46983.10000000',
  'size': '0.10000000',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441719,
  'price': '46986.60000000',
  'size': '0.05000000',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441718,
  'price': '46986.82000000',
  'size': '0.42560431',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441717,
  'price': '46986.82000000',
  'size': '0.01000000',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441716,
  'price': '46987.36000000',
  'size': '0.26000000',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441715,
  'price': '46988.91000000',
  'size': '0.03397818',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441714,
  'price': '46996.74000000',
  'size': '0.33600000',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441713,
  'price': '46996.74000000',
  'size': '0.00295712',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:11.956Z',
  'trade_id': 141441712,
  'price': '46996.74000000',
  'size': '0.18403990',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:09.541Z',
  'trade_id': 141441711,
  'price': '46996.74000000',
  'size': '0.00134192',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:09.175Z',
  'trade_id': 141441710,
  'price': '46996.74000000',
  'size': '0.00212493',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:09.175Z',
  'trade_id': 141441709,
  'price': '46996.74000000',
  'size': '0.00573750',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:09.175Z',
  'trade_id': 141441708,
  'price': '46996.74000000',
  'size': '0.00254902',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:08.64Z',
  'trade_id': 141441707,
  'price': '46996.56000000',
  'size': '0.01111827',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:08.64Z',
  'trade_id': 141441706,
  'price': '46995.58000000',
  'size': '0.00122429',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:08.64Z',
  'trade_id': 141441705,
  'price': '46994.66000000',
  'size': '0.00299390',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:08.64Z',
  'trade_id': 141441704,
  'price': '46993.24000000',
  'size': '0.00137145',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:08.64Z',
  'trade_id': 141441703,
  'price': '46990.39000000',
  'size': '0.04387209',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:08.64Z',
  'trade_id': 141441702,
  'price': '46990.39000000',
  'size': '0.04239446',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:08.64Z',
  'trade_id': 141441701,
  'price': '46990.39000000',
  'size': '0.00138410',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:07.389Z',
  'trade_id': 141441700,
  'price': '46990.38000000',
  'size': '0.05961449',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:07.139Z',
  'trade_id': 141441699,
  'price': '46984.43000000',
  'size': '0.00679844',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:07.062Z',
  'trade_id': 141441698,
  'price': '46984.44000000',
  'size': '0.00101662',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:07.038Z',
  'trade_id': 141441697,
  'price': '46980.20000000',
  'size': '0.42585995',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:06.987Z',
  'trade_id': 141441696,
  'price': '46971.31000000',
  'size': '0.25270000',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:06.963Z',
  'trade_id': 141441695,
  'price': '46971.31000000',
  'size': '0.07950150',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:06.951Z',
  'trade_id': 141441694,
  'price': '46971.31000000',
  'size': '0.35170551',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:06.943Z',
  'trade_id': 141441693,
  'price': '46971.31000000',
  'size': '0.06979832',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:06.943Z',
  'trade_id': 141441692,
  'price': '46971.31000000',
  'size': '0.02602121',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:05.428Z',
  'trade_id': 141441691,
  'price': '46971.31000000',
  'size': '0.01053717',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:04.255Z',
  'trade_id': 141441690,
  'price': '46971.31000000',
  'size': '0.00101711',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:03.747Z',
  'trade_id': 141441689,
  'price': '46970.66000000',
  'size': '0.00573750',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:03.747Z',
  'trade_id': 141441688,
  'price': '46970.56000000',
  'size': '0.01606000',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:03.739Z',
  'trade_id': 141441687,
  'price': '46970.73000000',
  'size': '0.00367479',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:02.855Z',
  'trade_id': 141441686,
  'price': '46967.66000000',
  'size': '0.00039223',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:02.842Z',
  'trade_id': 141441685,
  'price': '46954.69000000',
  'size': '0.00274749',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:02.208Z',
  'trade_id': 141441684,
  'price': '46966.15000000',
  'size': '0.00051921',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:01.504Z',
  'trade_id': 141441683,
  'price': '46966.53000000',
  'size': '0.00260000',
  'side': 'buy'},
 {'time': '2021-03-05T08:21:01.106Z',
  'trade_id': 141441682,
  'price': '46966.54000000',
  'size': '0.00030111',
  'side': 'sell'},
 {'time': '2021-03-05T08:21:00.254Z',
  'trade_id': 141441681,
  'price': '46966.53000000',
  'size': '0.00030219',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:58.588Z',
  'trade_id': 141441680,
  'price': '46966.54000000',
  'size': '0.00101700',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:58.427Z',
  'trade_id': 141441679,
  'price': '46966.54000000',
  'size': '0.00101734',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:58.03Z',
  'trade_id': 141441678,
  'price': '46973.22000000',
  'size': '0.00016973',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:56.835Z',
  'trade_id': 141441677,
  'price': '46956.52000000',
  'size': '0.00283227',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:56.371Z',
  'trade_id': 141441676,
  'price': '46954.46000000',
  'size': '0.01395000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:55.617Z',
  'trade_id': 141441675,
  'price': '46978.70000000',
  'size': '0.00380304',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:55.504Z',
  'trade_id': 141441674,
  'price': '46990.08000000',
  'size': '0.12360722',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:55.44Z',
  'trade_id': 141441673,
  'price': '46990.08000000',
  'size': '0.00053118',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:53.577Z',
  'trade_id': 141441672,
  'price': '46972.83000000',
  'size': '0.00137150',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:53.577Z',
  'trade_id': 141441671,
  'price': '46972.83000000',
  'size': '0.00180649',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:53.577Z',
  'trade_id': 141441670,
  'price': '46972.83000000',
  'size': '0.00142201',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:52.148Z',
  'trade_id': 141441669,
  'price': '46969.64000000',
  'size': '0.09919403',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:51.998Z',
  'trade_id': 141441668,
  'price': '46967.85000000',
  'size': '0.00130000',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:51.998Z',
  'trade_id': 141441667,
  'price': '46967.44000000',
  'size': '0.01000000',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:51.998Z',
  'trade_id': 141441666,
  'price': '46966.39000000',
  'size': '0.10000000',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:51.301Z',
  'trade_id': 141441665,
  'price': '46956.56000000',
  'size': '0.00015485',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:50.303Z',
  'trade_id': 141441664,
  'price': '46949.00000000',
  'size': '0.48945049',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:49.491Z',
  'trade_id': 141441663,
  'price': '46949.00000000',
  'size': '0.01054951',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441662,
  'price': '46943.57000000',
  'size': '0.01916896',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441661,
  'price': '46943.58000000',
  'size': '0.09965829',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441660,
  'price': '46943.58000000',
  'size': '0.10000000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441659,
  'price': '46943.58000000',
  'size': '0.29323370',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441658,
  'price': '46943.63000000',
  'size': '0.63800000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441657,
  'price': '46950.37000000',
  'size': '0.01648000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441656,
  'price': '46950.39000000',
  'size': '0.05806245',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441655,
  'price': '46950.84000000',
  'size': '0.00733415',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441654,
  'price': '46950.90000000',
  'size': '0.26000000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441653,
  'price': '46951.38000000',
  'size': '0.05806245',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:46.642Z',
  'trade_id': 141441652,
  'price': '46957.00000000',
  'size': '0.10000000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:45.176Z',
  'trade_id': 141441651,
  'price': '46960.94000000',
  'size': '0.06596291',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:45.176Z',
  'trade_id': 141441650,
  'price': '46960.68000000',
  'size': '0.01606000',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:45.176Z',
  'trade_id': 141441649,
  'price': '46960.68000000',
  'size': '0.01606000',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:45.176Z',
  'trade_id': 141441648,
  'price': '46954.18000000',
  'size': '0.00139256',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:45.176Z',
  'trade_id': 141441647,
  'price': '46947.39000000',
  'size': '0.10935763',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:45.115Z',
  'trade_id': 141441646,
  'price': '46947.39000000',
  'size': '0.01059723',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:42.17Z',
  'trade_id': 141441645,
  'price': '46947.39000000',
  'size': '0.03133801',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:41.476Z',
  'trade_id': 141441644,
  'price': '46947.39000000',
  'size': '0.07276771',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:40.705Z',
  'trade_id': 141441643,
  'price': '46947.39000000',
  'size': '0.00053007',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:40.326Z',
  'trade_id': 141441642,
  'price': '46947.39000000',
  'size': '0.00015485',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:40.116Z',
  'trade_id': 141441641,
  'price': '46947.38000000',
  'size': '0.00231289',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:39.736Z',
  'trade_id': 141441640,
  'price': '46937.78000000',
  'size': '0.11501780',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:39.701Z',
  'trade_id': 141441639,
  'price': '46929.40000000',
  'size': '0.00005486',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:39.63Z',
  'trade_id': 141441638,
  'price': '46929.40000000',
  'size': '0.25310000',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:39.483Z',
  'trade_id': 141441637,
  'price': '46929.40000000',
  'size': '0.07994988',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:39.269Z',
  'trade_id': 141441636,
  'price': '46929.40000000',
  'size': '0.10866081',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:38.82Z',
  'trade_id': 141441635,
  'price': '46929.40000000',
  'size': '0.00035006',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:38.608Z',
  'trade_id': 141441634,
  'price': '46908.29000000',
  'size': '0.02985014',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:38.608Z',
  'trade_id': 141441633,
  'price': '46919.42000000',
  'size': '0.04480030',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:38.608Z',
  'trade_id': 141441632,
  'price': '46919.42000000',
  'size': '0.02430000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:38.608Z',
  'trade_id': 141441631,
  'price': '46919.42000000',
  'size': '0.02040000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:36.244Z',
  'trade_id': 141441630,
  'price': '46919.43000000',
  'size': '0.00085352',
  'side': 'sell'},
 {'time': '2021-03-05T08:20:35.485Z',
  'trade_id': 141441629,
  'price': '46923.07000000',
  'size': '0.09318693',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:35.485Z',
  'trade_id': 141441628,
  'price': '46923.14000000',
  'size': '0.01648000',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:35.485Z',
  'trade_id': 141441627,
  'price': '46929.39000000',
  'size': '0.00242800',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:35.485Z',
  'trade_id': 141441626,
  'price': '46929.39000000',
  'size': '0.00434200',
  'side': 'buy'},
 {'time': '2021-03-05T08:20:34.989Z',
  'trade_id': 141441625,
  'price': '46929.40000000',
  'size': '0.00059366',
  'side': 'sell'}]

In [26]:
r = requests.get('https://api.pro.coinbase.com/products/BTC-USD/trades', params=params)

In [27]:
pd.DataFrame(r.json())

                        time   trade_id           price        size  side
0   2021-02-27T20:01:17.869Z  139133595  47493.29000000  0.00036091   buy
1   2021-02-27T20:01:17.019Z  139133594  47493.30000000  0.01938034  sell
2   2021-02-27T20:01:17.019Z  139133593  47493.30000000  0.02186743  sell
3   2021-02-27T20:01:16.243Z  139133592  47493.29000000  0.00100000   buy
4   2021-02-27T20:01:16.192Z  139133591  47493.29000000  0.00094500   buy
..                       ...        ...             ...         ...   ...
95  2021-02-27T20:01:01.208Z  139133500  47537.87000000  0.03028007  sell
96  2021-02-27T20:01:01.208Z  139133499  47536.73000000  0.00100000  sell
97  2021-02-27T20:01:01.208Z  139133498  47536.73000000  0.00019506  sell
98  2021-02-27T20:01:01.136Z  139133497  47532.00000000  0.00010466  sell
99   2021-02-27T20:01:01.01Z  139133496  47531.99000000  0.10896126   buy

[100 rows x 5 columns]

# Websocket

NameError: name 'self' is not defined

# Test Loading to Firebase

In [4]:
!pip install requests 
#!pip install python-firebase
!pip install git+https://github.com/ozgur/python-firebase

Requirement already satisfied: requests in /Users/Armand/anaconda3/lib/python3.6/site-packages (2.13.0)
Collecting git+https://github.com/ozgur/python-firebase
  Cloning https://github.com/ozgur/python-firebase to /private/var/folders/m2/04rc3r_96tdb3y332gktbpgr0000gn/T/pip-req-build-21vdwqfe
Requirement already satisfied: requests>=1.1.0 in /Users/Armand/anaconda3/lib/python3.6/site-packages (from python-firebase==1.2.1) (2.13.0)

In [5]:
from firebase import firebase

In [34]:
my_firebase = firebase.FirebaseApplication('https://test-random-305921-default-rtdb.firebaseio.com/', None)
test=my_firebase.delete('/websocket_level2', '-MUov9xInHpYYCLE493B')
print(test)

None

In [29]:
#import json
#with open('order_book.', 'w') as outfile:
#    json.dump(order_book, outfile)

In [17]:
result = my_firebase.get('/users', None)
print(result)

None

In [199]:
result = my_firebase.get('/trades', None)
pd.DataFrame(result).T.shape

(0, 0)

In [96]:
new_user='Armand Sauzay'
result = my_firebase.post('/users', new_user)
print(result)
my_firebase.get('/users', '')

{'name': '-MUltTw97D29xF1-FdbW'}

{'-MUltTw97D29xF1-FdbW': 'Armand Sauzay'}

In [102]:
my_firebase.delete('/users', '')

In [111]:
datas=[{'ask': '1527.13',
 'bid': '1526.51',
 'price': '1527.33',
 'size': '0.03129026',
 'time': '2021-03-01T19:09:39.714226Z',
 'trade_id': 89783839,
 'volume': '314003.92976961'}
 , 
 {'ask': '1527.13',
 'bid': '1526.51',
 'price': '1527.33',
 'size': '0.03129026',
 'time': '2021-03-01T19:09:39.714226Z',
 'trade_id': 89783839,
 'volume': '314003.92976961'}
]

In [112]:
data={'ask': '1527.13',
 'bid': '1526.51',
 'price': '1527.33',
 'size': '0.03129026',
 'time': '2021-03-01T19:09:39.714226Z',
 'trade_id': 89783839,
 'volume': '314003.92976961'}

In [122]:
result=my_firebase.post('/trades', datas)
print(result)

{'name': '-MUluQWBqsUwJTcXzztF'}

In [114]:
my_firebase.delete('/trades', '')

In [139]:
pd.DataFrame(my_firebase.get('/trades', '')).T.reset_index(drop=True)

,ask,bid,price,size,time,trade_id,volume
0,47672.35,47672.34,47672.34,0.00337311,2021-03-02T18:55:38.193304Z,140396236,18263.23675841
1,47672.35,47672.34,47672.34,0.00107518,2021-03-02T18:55:41.11686Z,140396244,18263.23675841
2,47672.35,47672.34,47672.34,0.01470698,2021-03-02T18:55:43.994527Z,140396245,18263.23675841
3,47688.68,47688.67,47688.68,0.00038639,2021-03-02T18:55:46.999105Z,140396260,18263.23675841
4,47701.99,47699.61,47698.63,0.00058462,2021-03-02T18:55:48.583173Z,140396268,18263.23675841
...,...,...,...,...,...,...,...
443,47384.54,47377.65,47377.3,0.02396846,2021-03-02T19:13:45.169496Z,140402769,17589.90929173
444,47377.93,47371.67,47376.98,0.00063277,2021-03-02T19:13:48.463949Z,140402782,17589.90929173
445,47383.45,47383.44,47386.48,0.01930358,2021-03-02T19:13:50.913865Z,140402789,17589.90929173
446,47380.69,47380.68,47380.69,0.00038885,2021-03-02T19:13:54.016019Z,140402803,17589.90929173
447,47380.69,47380.68,47380.69,0.00088417,2021-03-02T19:13:56.111257Z,140402812,17589.90929173

In [254]:
def dataframe_order_book(all):
  #data postprocessing
  df=pd.DataFrame(test).T.reset_index(drop=True)
  df['bids']=pd.DataFrame(df['bids'].to_list())
  df[['bid_price','bid_vol', 'bid_n_order']]=pd.DataFrame(df['bids'].to_list())
  df['asks']=pd.DataFrame(df['asks'].to_list())
  df[['ask_price','ask_vol', 'ask_n_order']]=pd.DataFrame(df['asks'].to_list())
  df.drop('bids', inplace=True, axis=1)
  df.drop('asks', inplace=True, axis=1)
  df.drop_duplicates()
  return df

In [255]:
import time

In [1]:
test=my_firebase.get('/trades', '')
print(test)

NameError: name 'my_firebase' is not defined

In [1]:
my_firebase = firebase.FirebaseApplication('https://test-random-305921-default-rtdb.firebaseio.com/', None)
test=my_firebase.get('/order_book', '')
print(pd.DataFrame(test).T.reset_index(drop=True).shape)
time.sleep(60)
test=my_firebase.get('/order_book', '')
print(pd.DataFrame(test).T.reset_index(drop=True).shape)

NameError: name 'firebase' is not defined

In [297]:
df=pd.DataFrame(test).T.reset_index(drop=True)
df

,asks,bids,sequence,time
0,"[[50950.05, 0.28, 1]]","[[50944.57, 0.01606, 1]]",22250329372,2021-03-03T23:26:40.402086
1,"[[50950.65, 0.18665277, 1]]","[[50944.33, 0.01606, 1]]",22250330782,2021-03-03T23:26:42.564591
2,"[[50951.08, 0.21794412, 1]]","[[50951.07, 1.49354662, 8]]",22250331601,2021-03-03T23:26:44.860096
3,"[[50951.08, 0.3726966, 2]]","[[50951.07, 1.14525776, 6]]",22250331985,2021-03-03T23:26:46.974367
4,"[[50960.56, 0.00169816, 1]]","[[50952.03, 0.28, 1]]",22250332698,2021-03-03T23:26:49.214095
...,...,...,...,...
693,"[[50667.21, 0.03254, 2]]","[[50653.43, 0.01606, 1]]",22251126980,2021-03-03T23:51:39.132511
694,"[[50665.84, 0.01606, 1]]","[[50656.23, 0.01606, 1]]",22251128870,2021-03-03T23:51:41.284053
695,"[[50661.79, 0.07340966, 3]]","[[50657.65, 0.28, 1]]",22251130716,2021-03-03T23:51:43.452299
696,"[[50650.46, 0.51571114, 5]]","[[50650.45, 0.28, 1]]",22251131738,2021-03-03T23:51:45.605952
697,"[[50650.46, 4.61647661, 13]]","[[50650.45, 0.01164193, 3]]",22251132436,2021-03-03T23:51:47.754522

In [286]:
df['time'].head()

0    2021-03-03T23:26:40.402086
1    2021-03-03T23:26:42.564591
2    2021-03-03T23:26:44.860096
3    2021-03-03T23:26:46.974367
4    2021-03-03T23:26:49.214095
Name: time, dtype: object

In [291]:
time_diff=pd.to_datetime(df['time'])-pd.to_datetime(df['time'].shift(1))

In [295]:
min(time_diff[1:])

Timedelta('0 days 00:00:02.101425')

In [160]:
dataframe_order_book(test)

,sequence,time,bid_price,bid_vol,bid_n_order,ask_price,ask_vol,ask_n_order
0,22195286146,2021-03-02T18:55:39.965773,47672.34,0.95242759,20,47672.35,0.19771833,6
1,22195286861,2021-03-02T18:55:42.653463,47672.34,1.0414105,23,47672.35,0.16779153,5
2,22195287437,2021-03-02T18:55:45.011274,47672.34,1.03025255,24,47672.35,0.16779153,5
3,22195289309,2021-03-02T18:55:47.441547,47688.67,1.70408471,11,47688.68,0.0016865,2
4,22195291214,2021-03-02T18:55:49.818212,47709.38,0.02179303,1,47709.39,0.02607892,1
...,...,...,...,...,...,...,...,...
503,22196168597,2021-03-02T19:16:13.112805,47163.57,0.06194854,1,47169.11,0.0226,1
504,22196170798,2021-03-02T19:16:15.518342,47171.59,0.00390162,1,47174.93,0.0226,1
505,22196172431,2021-03-02T19:16:17.900885,47167.48,0.07484052,2,47176,0.00183146,1
506,22196174797,2021-03-02T19:16:20.286881,47181.39,0.42367624,1,47181.4,0.01977949,1
507,22196176938,2021-03-02T19:16:22.755597,47181.86,0.00172669,1,47181.87,1.8345487,7

In [134]:
pd.DataFrame(test).T.reset_index(drop=True)

,asks,bids,sequence,time
0,"[[47672.35, 0.19771833, 6]]","[[47672.34, 0.95242759, 20]]",22195286146,2021-03-02T18:55:39.965773
1,"[[47672.35, 0.16779153, 5]]","[[47672.34, 1.0414105, 23]]",22195286861,2021-03-02T18:55:42.653463
2,"[[47672.35, 0.16779153, 5]]","[[47672.34, 1.03025255, 24]]",22195287437,2021-03-02T18:55:45.011274
3,"[[47688.68, 0.0016865, 2]]","[[47688.67, 1.70408471, 11]]",22195289309,2021-03-02T18:55:47.441547
4,"[[47709.39, 0.02607892, 1]]","[[47709.38, 0.02179303, 1]]",22195291214,2021-03-02T18:55:49.818212
...,...,...,...,...
159,"[[47772.5, 0.25910702, 11]]","[[47772.49, 0.68457928, 3]]",22195507342,2021-03-02T19:02:08.512828
160,"[[47772.5, 0.12499272, 13]]","[[47772.49, 0.76038156, 6]]",22195508327,2021-03-02T19:02:10.918070
161,"[[47772.5, 0.01275652, 4]]","[[47772.49, 1.07157694, 7]]",22195509679,2021-03-02T19:02:13.642124
162,"[[47777.42, 1.78476372, 6]]","[[47777.41, 0.00100857, 1]]",22195512221,2021-03-02T19:02:16.188478
163,"[[47777.42, 5, 1]]","[[47777.41, 0.63173011, 5]]",22195513269,2021-03-02T19:02:18.636274

In [4]:
!pip install git+https://github.com/ozgur/python-firebase

Collecting git+https://github.com/ozgur/python-firebase
  Cloning https://github.com/ozgur/python-firebase to /private/var/folders/m2/04rc3r_96tdb3y332gktbpgr0000gn/T/pip-req-build-isi9eall
Requirement already satisfied: requests>=1.1.0 in /Users/Armand/anaconda3/lib/python3.6/site-packages (from python-firebase==1.2.1) (2.13.0)

In [7]:

from firebase import firebase
import pandas as pd
my_firebase = firebase.FirebaseApplication('https://test-random-305921-default-rtdb.firebaseio.com/', None)
test_trades=my_firebase.get('/trades', '') #will get you the data in json format
pd.DataFrame(test_trades).T.reset_index(drop=True) #will get you the data in dataframe format

Empty DataFrame
Columns: []
Index: []

In [57]:
#test_order_book=my_firebase.get('/websocket_order_book', '')
#len(test_order_book)
test_trades=my_firebase.get('/websocket_trades', '')
len(test_trades)

153648

In [58]:
df_order_book=pd.DataFrame(test_order_book).T.reset_index(drop=True)

In [59]:
df_order_book.head()

,maker_order_id,price,product_id,sequence,side,size,taker_order_id,time,trade_id,type
0,533e5cd3-442b-414b-b88e-1ea76f1c2153,46571.52,BTC-USD,22321753637,sell,0.00050229,71de4e5b-8806-4f5d-b0a9-a4588d38fb12,2021-03-05T09:00:28.705610Z,141449862,match
1,533e5cd3-442b-414b-b88e-1ea76f1c2153,46571.52,BTC-USD,22321753637,sell,0.00050229,71de4e5b-8806-4f5d-b0a9-a4588d38fb12,2021-03-05T09:00:28.705610Z,141449862,match
2,02a041e2-f6d4-42e1-99c4-6e420888b422,46571.51,BTC-USD,22321753724,buy,0.0975307,72f3d2e8-4635-40ab-bfad-219989cd4e44,2021-03-05T09:00:28.994933Z,141449863,match
3,02a041e2-f6d4-42e1-99c4-6e420888b422,46571.51,BTC-USD,22321753724,buy,0.0975307,72f3d2e8-4635-40ab-bfad-219989cd4e44,2021-03-05T09:00:28.994933Z,141449863,match
4,3c4e649d-38c7-46dc-8bf3-a6a727b87282,46571.51,BTC-USD,22321753726,buy,0.0024693,72f3d2e8-4635-40ab-bfad-219989cd4e44,2021-03-05T09:00:28.994933Z,141449864,match

In [46]:
df_order_book.type.value_counts()

l2update         171162
snapshot              3
subscriptions         3
Name: type, dtype: int64

In [48]:
df_order_book[df_order_book['type']=='snapshot']

,channels,type,asks,bids,product_id,changes,time
2,NaN,snapshot,"[[46569.37, 0.50000000], [46569.87, 0.19000000...","[[46560.04, 0.19000000], [46559.88, 0.01606000...",BTC-USD,NaN,NaN
3,NaN,snapshot,"[[46571.02, 0.19000000], [46571.51, 0.05000000...","[[46564.19, 0.19000000], [46561.50, 0.02794022...",BTC-USD,NaN,NaN
99045,NaN,snapshot,"[[47403.40, 0.18000000], [47403.92, 0.50000000...","[[47397.99, 0.10000000], [47394.71, 0.01606000...",BTC-USD,NaN,NaN

In [50]:
df_order_book.iloc[99045+1]

channels                                 NaN
type                                l2update
asks                                     NaN
bids                                     NaN
product_id                           BTC-USD
changes       [[sell, 47403.39, 0.50000000]]
time             2021-03-05T12:15:40.022838Z
Name: 99046, dtype: object